# Generated by Django 3.1.8 on 2021-06-03 08:51

from django.db import migrations, models
import tagify.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('languages', tagify.models.TagField(verbose_name='languages')),
            ],
        ),
    ]
