# Generated by Django 2.0.3 on 2018-04-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'verbose_name': 'People',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PeopleFruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_id', models.IntegerField(verbose_name='people_id')),
                ('fruit', models.CharField(max_length=30, verbose_name='fruit')),
            ],
            options={
                'verbose_name': 'People-Fruits',
                'verbose_name_plural': 'People-Fruits',
            },
        ),
    ]
